"""agrega areas_de_vida_json a cartas_natales

Revision ID: 094ddbeaaf56
Revises: ad06b5c1e53f
Create Date: 2026-07-25 11:10:32.393389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094ddbeaaf56'
down_revision: Union[str, Sequence[str], None] = 'ad06b5c1e53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areas_de_vida_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.drop_column('areas_de_vida_json')

    # ### end Alembic commands ###
