"""crea producto_configs y productos_generados

Revision ID: 71bee81d92ba
Revises: 7960b61645c4
Create Date: 2026-08-07 19:21:29.489900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bee81d92ba'
down_revision: Union[str, Sequence[str], None] = '7960b61645c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_configs',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('instrucciones_usuario_template', sa.Text(), nullable=False),
    sa.Column('criterios_json', sa.Text(), nullable=True),
    sa.Column('temas_a_criterios_json', sa.Text(), nullable=True),
    sa.Column('secciones_json', sa.Text(), nullable=False),
    sa.Column('inputs_requeridos_json', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('productos_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carta_id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('contenido_json', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carta_id'], ['cartas_natales.id'], ),
    sa.ForeignKeyConstraint(['producto_codigo'], ['producto_configs.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos_generados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_generados_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_generados_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_generados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_generados_token'))
        batch_op.drop_index(batch_op.f('ix_productos_generados_id'))

    op.drop_table('productos_generados')
    op.drop_table('producto_configs')
    # ### end Alembic commands ###
