"""crea tabla horoscopos_generados

Revision ID: 7960b61645c4
Revises: a8a53f98f794
Create Date: 2026-07-30 10:23:29.489025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7960b61645c4'
down_revision: Union[str, Sequence[str], None] = 'a8a53f98f794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horoscopos_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadencia', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('contenido_json', sa.Text(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horoscopos_generados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horoscopos_generados_cadencia'), ['cadencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_horoscopos_generados_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_horoscopos_generados_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horoscopos_generados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horoscopos_generados_id'))
        batch_op.drop_index(batch_op.f('ix_horoscopos_generados_fecha'))
        batch_op.drop_index(batch_op.f('ix_horoscopos_generados_cadencia'))

    op.drop_table('horoscopos_generados')
    # ### end Alembic commands ###
