"""agrega fecha_solicitud_compra a cartas_natales

Revision ID: a8a53f98f794
Revises: f646169a347c
Create Date: 2026-07-27 15:25:51.898910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a53f98f794'
down_revision: Union[str, Sequence[str], None] = 'f646169a347c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_solicitud_compra', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.drop_column('fecha_solicitud_compra')

    # ### end Alembic commands ###
