"""agrega nombre_reporte, email, token, enviado y fecha_envio a cartas_natales

Revision ID: ad06b5c1e53f
Revises: ebe4e784d7ff
Create Date: 2026-07-23 12:24:40.519540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad06b5c1e53f'
down_revision: Union[str, Sequence[str], None] = 'ebe4e784d7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_reporte', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('enviado', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('fecha_envio', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cartas_natales_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_cartas_natales_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cartas_natales_token'))
        batch_op.drop_index(batch_op.f('ix_cartas_natales_email'))
        batch_op.drop_column('fecha_envio')
        batch_op.drop_column('enviado')
        batch_op.drop_column('token')
        batch_op.drop_column('email')
        batch_op.drop_column('nombre_reporte')

    # ### end Alembic commands ###
