"""agrega genero a cartas_natales

Revision ID: f62051f24af8
Revises: 094ddbeaaf56
Create Date: 2026-07-25 11:16:03.630369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62051f24af8'
down_revision: Union[str, Sequence[str], None] = '094ddbeaaf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.drop_column('genero')

    # ### end Alembic commands ###
