"""agrega transitos_json a cartas_natales

Revision ID: f646169a347c
Revises: f62051f24af8
Create Date: 2026-07-25 15:59:35.512868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f646169a347c'
down_revision: Union[str, Sequence[str], None] = 'f62051f24af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transitos_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartas_natales', schema=None) as batch_op:
        batch_op.drop_column('transitos_json')

    # ### end Alembic commands ###
